### ISSUE TITLE
Automation with voice, use cases, insights and ideas

### ISSUE THREAD

**Issue by wadid** [doxgt/PlayGround#1]
Hi,

Very interesting! Thank you so much for giving me the idea of using AutoHotKey with cURL for automating things. I’ve tried working with Windows Voice Command and Speech-to-Text before, but the experience wasn’t great. Whisper with AHK might be the solution though, especially if you want to quickly send custom instructions to text generation models and get the result in the clipboard.

I wanted to ask, how much of your Windows and application usage have you successfully automated with voice and AHK, and what are some cool use cases? I’ve also seen some really interesting things you can do with platforms like make.com, for example, interfacing AI with a lot of different applications. Depending on your use cases, your ideas might give me valuable input and help with mine.

Also, do you have any microphone recommendations? I’m looking for something seamless and easy to use, that doesn’t need a big setup and isn’t too sensitive in handling. Ideally, something robust that I could also use while driving or clip onto a shirt. I’ve noticed I get poor results using the hands-free system in my car for text-to-speech (trying to automate that also a bit), and on my laptop mic isn’t great either. I only have a mic with some headphones, but I’d prefer not to always have to use headphones just for the mic.

Is there any way I can contact you by email or otherwise? Thanks!

**Comment by doxgt** [comment]
Hi Walid.   Even though less now than before, I do poke my head now and then onto this forum: https://forums.knowbrainer.com/

I definitely recommend you re-posting your questions to the above forum, whereby you'll get answers from a diverse group of aficionados.

If you're serious about "robotic process automation" on windows, Dragon by Nuance is still the #1 contender.  As far as I know, AI, in its current popularized form facing mass consumers, is really not ready for prime time in RPA.

Besides Dragon +/- AHK, there is Dragon with built-in advanced scripting.  Then there is [Talon](https://talonvoice.com/) for the more "hardcore".  And there are portable tools such as [VoiceMacro](https://www.voicemacro.net/).

Again, the KnowBrainer forum is where you are most likely to find your answers - including on speech recognition microphones.

Cheers!

**Comment by wadid** [comment]
I tried a couple of times to register in the forum but it just did not work. I tried a couple of times with different browsers. There seem to be some issues with the captcha.
I contacted the admin also but never got any response.
I wanted to ask if you can talk to the admin, maybe he responds to you?

**Comment by doxgt** [comment]
Have you tried emailing lunis@knowbrainer.com?  Or even calling 615-884-4558 x 1?

I am not familiar with the ever-changing nature of website gatekeeping.  They do get a fair amount of spam unfortunately, it seems.

The proprietor is usually fairly responsive.

**Comment by wadid** [comment]
I just sent him an email. so lets see if he responds.

**Comment by wadid** [comment]
Quite quickly I got an email by someone who seems to do some admin or support. He said he will forward my issue. That was quite long ago. Its quite difficult to get into that forum. The website also has many broken links (the shop at least). Let me ask you, do you need a dragon license for knowbrainer or can you use it without? I watched some of the tutorial videos and the side bar feature with all the commands looks really nice.

**Comment by doxgt** [comment]
A desktop Dragon license is a pre-requisite to using Knowbrainer indeed.

**Comment by wadid** [comment]
Ah ok then its not really interesting to me. It would complicate eveything too much and would also cost too much.

Did you experiment more with whisper or LLMs? I have to say I quite often use whispering as it is much faster to send prompts spoken than written. But it is a "locked" in experience by the "borders" of the applications. You cannot properly or reliably command tasks that are spanning different applications. Would be nice to easily activate all kind of dynamic automations that will then return you the results in the exact places where you need them.

Now with Anthropic delivering "computer use" beta version and OpenAI soon bringing out functionality to use GPTsin different apps, I kind of imagine that the business model of Knowbrainer is a bit threatened. Also considering the quality of models likewhisper, it seems also like a threat to Dragon I guess. Of course its still not properly usable in many cases, but new features are coming out super fast.

What is your opinion about this?

**Comment by doxgt** [comment]
No real opinion.  Let things play out.

If on Windows only, one could try VoiceMacro for commands and Whispering or equivalent for prose dictation.

https://forums.knowbrainer.com/forum/microsoft-windows-speech-recognition/1794-journey-with-windows-speech-recognition-macros-a-tale-of-discovery-and-sharing?p=1803#post1803

There is also Talon Voice (https://forums.knowbrainer.com/forum/third-party-command-utilities-vocola-unimacro-voicepower-python/5874-talon-voice-comments-experience-performance).

VoiceMacro + Whispering is not a bad way to go.
